name: Test

on:
  push:
    branches:
      - master
      - release
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "pypy-3.6", "pypy-3.7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pytest toolz==0.11.2
          python setup.py build_ext --inplace --without-cython
          pip install -e .
      - name: PyTest
        run: |
          pytest --doctest-modules cytoolz/
          # For convenience, make sure simple test commands work
          pytest
