name: Build wheels

on:
  # TODO" delete pull_request below when this is working
  pull_request:
  tags:
  push:
    branches:
      - master

jobs:
  wheels:
    name: "Build ${{ matrix.build }} wheel"
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Automaticaly generated via a script; one job each so we can investigate
          - {"os": "macos", "build": "cp36-macosx_x86_64, "arch": "x86_64"}
          - {"os": "macos", "build": "cp37-macosx_x86_64, "arch": "x86_64"}
          - {"os": "macos", "build": "cp38-macosx_arm64, "arch": "arm64"}
          - {"os": "macos", "build": "cp38-macosx_x86_64, "arch": "x86_64"}
          - {"os": "macos", "build": "cp39-macosx_arm64, "arch": "arm64"}
          - {"os": "macos", "build": "cp39-macosx_x86_64, "arch": "x86_64"}
          - {"os": "macos", "build": "cp310-macosx_arm64, "arch": "arm64"}
          - {"os": "macos", "build": "cp310-macosx_x86_64, "arch": "x86_64"}
          - {"os": "macos", "build": "pp37-macosx_x86_64, "arch": "x86_64"}
          - {"os": "macos", "build": "pp38-macosx_x86_64, "arch": "x86_64"}
          - {"os": "macos", "build": "pp39-macosx_x86_64, "arch": "x86_64"}
          - {"os": "ubuntu", "build": "cp36-manylinux_aarch64, "arch": "aarch64"}
          - {"os": "ubuntu", "build": "cp36-manylinux_i686, "arch": "i686"}
          - {"os": "ubuntu", "build": "cp36-manylinux_ppc64le, "arch": "ppc64le"}
          - {"os": "ubuntu", "build": "cp36-manylinux_s390x, "arch": "s390x"}
          - {"os": "ubuntu", "build": "cp36-manylinux_x86_64, "arch": "x86_64"}
          - {"os": "ubuntu", "build": "cp36-musllinux_aarch64, "arch": "aarch64"}
          - {"os": "ubuntu", "build": "cp36-musllinux_i686, "arch": "i686"}
          - {"os": "ubuntu", "build": "cp36-musllinux_ppc64le, "arch": "ppc64le"}
          - {"os": "ubuntu", "build": "cp36-musllinux_s390x, "arch": "s390x"}
          - {"os": "ubuntu", "build": "cp36-musllinux_x86_64, "arch": "x86_64"}
          - {"os": "ubuntu", "build": "cp37-manylinux_aarch64, "arch": "aarch64"}
          - {"os": "ubuntu", "build": "cp37-manylinux_i686, "arch": "i686"}
          - {"os": "ubuntu", "build": "cp37-manylinux_ppc64le, "arch": "ppc64le"}
          - {"os": "ubuntu", "build": "cp37-manylinux_s390x, "arch": "s390x"}
          - {"os": "ubuntu", "build": "cp37-manylinux_x86_64, "arch": "x86_64"}
          - {"os": "ubuntu", "build": "cp37-musllinux_aarch64, "arch": "aarch64"}
          - {"os": "ubuntu", "build": "cp37-musllinux_i686, "arch": "i686"}
          - {"os": "ubuntu", "build": "cp37-musllinux_ppc64le, "arch": "ppc64le"}
          - {"os": "ubuntu", "build": "cp37-musllinux_s390x, "arch": "s390x"}
          - {"os": "ubuntu", "build": "cp37-musllinux_x86_64, "arch": "x86_64"}
          - {"os": "ubuntu", "build": "cp38-manylinux_aarch64, "arch": "aarch64"}
          - {"os": "ubuntu", "build": "cp38-manylinux_i686, "arch": "i686"}
          - {"os": "ubuntu", "build": "cp38-manylinux_ppc64le, "arch": "ppc64le"}
          - {"os": "ubuntu", "build": "cp38-manylinux_s390x, "arch": "s390x"}
          - {"os": "ubuntu", "build": "cp38-manylinux_x86_64, "arch": "x86_64"}
          - {"os": "ubuntu", "build": "cp38-musllinux_aarch64, "arch": "aarch64"}
          - {"os": "ubuntu", "build": "cp38-musllinux_i686, "arch": "i686"}
          - {"os": "ubuntu", "build": "cp38-musllinux_ppc64le, "arch": "ppc64le"}
          - {"os": "ubuntu", "build": "cp38-musllinux_s390x, "arch": "s390x"}
          - {"os": "ubuntu", "build": "cp38-musllinux_x86_64, "arch": "x86_64"}
          - {"os": "ubuntu", "build": "cp39-manylinux_aarch64, "arch": "aarch64"}
          - {"os": "ubuntu", "build": "cp39-manylinux_i686, "arch": "i686"}
          - {"os": "ubuntu", "build": "cp39-manylinux_ppc64le, "arch": "ppc64le"}
          - {"os": "ubuntu", "build": "cp39-manylinux_s390x, "arch": "s390x"}
          - {"os": "ubuntu", "build": "cp39-manylinux_x86_64, "arch": "x86_64"}
          - {"os": "ubuntu", "build": "cp39-musllinux_aarch64, "arch": "aarch64"}
          - {"os": "ubuntu", "build": "cp39-musllinux_i686, "arch": "i686"}
          - {"os": "ubuntu", "build": "cp39-musllinux_ppc64le, "arch": "ppc64le"}
          - {"os": "ubuntu", "build": "cp39-musllinux_s390x, "arch": "s390x"}
          - {"os": "ubuntu", "build": "cp39-musllinux_x86_64, "arch": "x86_64"}
          - {"os": "ubuntu", "build": "cp310-manylinux_aarch64, "arch": "aarch64"}
          - {"os": "ubuntu", "build": "cp310-manylinux_i686, "arch": "i686"}
          - {"os": "ubuntu", "build": "cp310-manylinux_ppc64le, "arch": "ppc64le"}
          - {"os": "ubuntu", "build": "cp310-manylinux_s390x, "arch": "s390x"}
          - {"os": "ubuntu", "build": "cp310-manylinux_x86_64, "arch": "x86_64"}
          - {"os": "ubuntu", "build": "cp310-musllinux_aarch64, "arch": "aarch64"}
          - {"os": "ubuntu", "build": "cp310-musllinux_i686, "arch": "i686"}
          - {"os": "ubuntu", "build": "cp310-musllinux_ppc64le, "arch": "ppc64le"}
          - {"os": "ubuntu", "build": "cp310-musllinux_s390x, "arch": "s390x"}
          - {"os": "ubuntu", "build": "cp310-musllinux_x86_64, "arch": "x86_64"}
          - {"os": "ubuntu", "build": "pp37-manylinux_aarch64, "arch": "aarch64"}
          - {"os": "ubuntu", "build": "pp37-manylinux_i686, "arch": "i686"}
          - {"os": "ubuntu", "build": "pp37-manylinux_x86_64, "arch": "x86_64"}
          - {"os": "ubuntu", "build": "pp38-manylinux_aarch64, "arch": "aarch64"}
          - {"os": "ubuntu", "build": "pp38-manylinux_i686, "arch": "i686"}
          - {"os": "ubuntu", "build": "pp38-manylinux_x86_64, "arch": "x86_64"}
          - {"os": "ubuntu", "build": "pp39-manylinux_aarch64, "arch": "aarch64"}
          - {"os": "ubuntu", "build": "pp39-manylinux_i686, "arch": "i686"}
          - {"os": "ubuntu", "build": "pp39-manylinux_x86_64, "arch": "x86_64"}
          - {"os": "windows", "build": "cp36-win32, "arch": "x86"}
          - {"os": "windows", "build": "cp36-win_amd64, "arch": "AMD64"}
          - {"os": "windows", "build": "cp37-win32, "arch": "x86"}
          - {"os": "windows", "build": "cp37-win_amd64, "arch": "AMD64"}
          - {"os": "windows", "build": "cp38-win32, "arch": "x86"}
          - {"os": "windows", "build": "cp38-win_amd64, "arch": "AMD64"}
          - {"os": "windows", "build": "cp39-win32, "arch": "x86"}
          - {"os": "windows", "build": "cp39-win_amd64, "arch": "AMD64"}
          - {"os": "windows", "build": "cp310-win32, "arch": "x86"}
          - {"os": "windows", "build": "cp310-win_amd64, "arch": "AMD64"}
          - {"os": "windows", "build": "pp37-win_amd64, "arch": "AMD64"}
          - {"os": "windows", "build": "pp38-win_amd64, "arch": "AMD64"}
          - {"os": "windows", "build": "pp39-win_amd64, "arch": "AMD64"}

    steps:
      - name: Setup QEMU
        if: matrix.os == 'ubuntu'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_ARCHS: ${{ matrix.arch }}
      - name: List wheels
        run: |
          ls -al wheelhouse/
      - name: "Upload wheels"
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: wheelhouse/*.whl
          retention-days: 1
